### ISSUE TITLE
Leaves signal-cli processes eating up memory

### ISSUE THREAD

**Issue by lindhor** [dadevel/alertmanager-signal-receiver#12]
I have configured alertmanager-signal-receiver to run in a container on a Synology NAS and have Prometheus Alertmanager running on the same NAS. I have noticed several times that the memory and swap of the NAS runs out, freezing the whole system.

Looking at what processes are using memory I see hundreds of signal-cli processes each looking something like this.
```
1000       963 34.8  5.7 2948868 103924 ?      Sl   10:06   0:04      \_ java -classpath /app/lib/signal-cli-0.10.7.jar:/app/lib/lib.jar:/app/lib/bcprov-jdk15on-1.70.jar:/app/lib/jackson-annotations-2.13.3.jar:/app/lib/jackson-core-2.13.3.jar:/app/lib/signal-service-java-2.15.3_unofficial_49.jar:/app/lib/jackson-databind-2.13.3.jar:/app/lib/argparse4j-0.9.0.jar:/app/lib/dbus-java-transport-native-unixsocket-4.1.0.jar:/app/lib/logback-classic-1.2.11.jar:/app/lib/jul-to-slf4j-1.7.36.jar:/app/lib/dbus-java-core-4.1.0.jar:/app/lib/HikariCP-5.0.1.jar:/app/lib/slf4j-api-1.7.36.jar:/app/lib/logback-core-1.2.11.jar:/app/lib/protobuf-javalite-3.11.4.jar:/app/lib/sqlite-jdbc-3.36.0.3.jar:/app/lib/threetenbp-1.3.6.jar:/app/lib/libphonenumber-8.12.48.jar:/app/lib/libsignal-client-0.17.0.jar:/app/lib/okhttp-4.9.2.jar:/app/lib/okio-jvm-2.10.0.jar:/app/lib/rxjava-3.0.13.jar:/app/lib/kotlin-stdlib-1.4.20.jar:/app/lib/kotlin-stdlib-common-1.4.20.jar:/app/lib/reactive-streams-1.0.3.jar:/app/lib/annotations-13.0.jar org.asamk.signal.Main --config ./data --username +4612345678 send --group xxxxxDCISWbwrVJNGA46o8Z2uQ=
1000       963 36.0  6.9 2966312 124140 ?      Sl   10:06   0:06      \_ java -classpath /app/lib/signal-cli-0.10.7.jar:/app/lib/lib.jar:/app/lib/bcprov-jdk15on-1.70.jar:/app/lib/jackson-annotations-2.13.3.jar:/app/lib/jackson-core-2.13.3.jar:/app/lib/signal-service-java-2.15.3_unofficial_49.jar:/app/lib/jackson-databind-2.13.3.jar:/app/lib/argparse4j-0.9.0.jar:/app/lib/dbus-java-transport-native-unixsocket-4.1.0.jar:/app/lib/logback-classic-1.2.11.jar:/app/lib/jul-to-slf4j-1.7.36.jar:/app/lib/dbus-java-core-4.1.0.jar:/app/lib/HikariCP-5.0.1.jar:/app/lib/slf4j-api-1.7.36.jar:/app/lib/logback-core-1.2.11.jar:/app/lib/protobuf-javalite-3.11.4.jar:/app/lib/sqlite-jdbc-3.36.0.3.jar:/app/lib/threetenbp-1.3.6.jar:/app/lib/libphonenumber-8.12.48.jar:/app/lib/libsignal-client-0.17.0.jar:/app/lib/okhttp-4.9.2.jar:/app/lib/okio-jvm-2.10.0.jar:/app/lib/rxjava-3.0.13.jar:/app/lib/kotlin-stdlib-1.4.20.jar:/app/lib/kotlin-stdlib-common-1.4.20.jar:/app/lib/reactive-streams-1.0.3.jar:/app/lib/annotations-13.0.jar org.asamk.signal.Main --config ./data --username +4612345678 send --group xxxxxDCISWbwrVJNGA46o8Z2uQ=
```
In general it seems like each signal-cli process takes about 20 seconds to complete when everything works.

In the docker log I see this frequently, but not when just restarted before the zombies start occurring:
```
serverrequest handler failed: signal-cli: command execution failed: INFO  AccountsStore - Config file is in use by another instance, waiting…
: signal: killed
```
Restarting the container and it works fine again for a while. I do get notified using the configured signal group again. No "zombie" processes left for a while before it starts happening again. I see this issue happening every few hours. To me it looks like some kind of race condition.

Googling around I found this issue https://github.com/AsamK/signal-cli/issues/51

So, could it be that we will need some kind of semaphore to avoid new signal-cli processes to start if one is already running at https://github.com/dadevel/alertmanager-signal-receiver/blob/main/signal/signal.go#L41 ? I.e. wait for the running one to finish.

**Comment by dadevel** [comment]
Hey, thanks for reporting the bug. I probably never hit the race condition because my message volume is relatively low. I might have some free time tomorrow to have a look, but no promises.

**Comment by dadevel** [comment]
Hi @lindhor, I added a mutex around signal-cli and pushed a container image with the fix to `ghcr.io/dadevel/signal-receiver:signal-lock`. Maybe you can give it a try?

**Comment by lindhor** [comment]
Thank you so much! I just downloaded and started it without any problem anyway. I'll leave it running for a few days just to make sure, but looks good.

**Comment by lindhor** [comment]
Still looks fine, so I think you can safely consider this fixed. Thanks again!
