### ISSUE TITLE
1.4.1 release doesn't work

### ISSUE THREAD

**Issue by orangepeelbeef** [dadevel/alertmanager-signal-receiver#20]
I had my signal receiver container auto-updating with watchtower, and my container is now busted.

serverrequest handler failed: signal-cli: command execution failed: WARN  Manager - Failed to call libsignal-client: /tmp/14960838443535371721libsignal_jni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/14960838443535371721libsignal_jni.so)
Missing required native library dependency: libsignal-client
: exit status 1

trying to downgrade back to 1.4.0 tells me my config file is a newer version and no longer compatible.  :(

**Comment by dadevel** [comment]
Yeah, sorry about that. Something changed in `signal-cli`. Unfortunately I don't have time at the moment to look into it. Maybe delete the named volume and use the old version.

**Comment by micah** [comment]
@orangepeelbeef did you try this? I'm also running into this issue.

**Comment by micah** [comment]
@dadevel I took your Dockerfile, and changed from bullseye to bookworm, and built it and things worked afterwards. So I think this is a fairly easy fix.

**Comment by dadevel** [comment]
Oh thanks. I'll push the fix tonight.

**Comment by orangepeelbeef** [comment]
Glad you got it working, I ended up switching over to
https://github.com/bbernhard/signal-cli-rest-api

**Comment by dadevel** [comment]
I pushed the fixed image. Thanks to @micah again for the tip with Debian Bookworm.
