### ISSUE TITLE
Can send to one specific user but can't send to group

### ISSUE THREAD

**Issue by Tarmik0s** [dadevel/alertmanager-signal-receiver#6]
Hi,

I was able to register and verify my number, then I tried to send a simple message to another user and it is working alright but when I create a group I cannot send any message to it. Hope you can help me with this, thank you so much.

There is also this warning error:

WARN Manager - The Signal protocol expects that incoming messages are regularly received.

**Comment by dadevel** [comment]
I send messages to groups with signal-cli every day. So it should work. I'm not sure what causes your problem. Please provide all commands together with their output (setting up signal-cli, sending a message to a user and to a group) to aid in debugging. Oh, and don't forget to redact any phone numbers.
